"""retention rules

Revision ID: 2c40bb4bc93f
Revises: 2419198ea4ed
Create Date: 2026-06-15 09:50:15.247597+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  (von autogenerierten SQLModel-Typen benoetigt)
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c40bb4bc93f'
down_revision: str | None = '2419198ea4ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_retention_rules_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_rules')),
    sa.UniqueConstraint('project_id', 'category', name='retention_rule_scope', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_retention_rules_project_id'), 'retention_rules', ['project_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: retention_until fuer Dokumente ohne Aufbewahrungsfrist setzen
    # (Mindest-Default aus settings.default_retention_days, Art. 5(1e)).
    from dms_core.config import settings

    days = settings.default_retention_days
    if days > 0:
        op.execute(
            sa.text(
                "UPDATE documents SET retention_until = "
                "(created_at AT TIME ZONE 'UTC')::date + (:days || ' days')::interval "
                "WHERE retention_until IS NULL"
            ).bindparams(days=days)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_rules_project_id'), table_name='retention_rules')
    op.drop_table('retention_rules')
    # ### end Alembic commands ###
