"""add file_name to document_versions

Revision ID: 6f826ad78867
Revises: 2a4660993b0b
Create Date: 2026-06-14 22:11:13.290624+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (von autogenerierten SQLModel-Typen benoetigt)


# revision identifiers, used by Alembic.
revision: str = '6f826ad78867'
down_revision: str | None = '2a4660993b0b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_versions', sa.Column('file_name', sa.String(length=400), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_versions', 'file_name')
    # ### end Alembic commands ###
